Zero gravity dev
muxi-mini-project/2021-ZeroGravity-backend pull request #1
Opened 2021-01-19 09:29 UTC by gongna-au

Zero gravity dev

2021-01-19 09:37 UTC, JacksieCheung commented
pr的标题注意规范，写ZeroGravity_dev是可以的，但最好是根据这次更改的来命名。这次更改的主要是sql文件，就可以写成"add db.sql" 或者写中文也可以。提交的描述可以写详细的描述，不过一般不写也可以。

2021-01-19 10:02 UTC, JacksieCheung commented on db.sql
> +    accountPassword varchar2(255) not null,
直接password就行了，而且sql不应该用驼峰命名，应该用下划线。

2021-01-19 10:02 UTC, JacksieCheung commented on db.sql
> +    account varchar2(255) not null,
这个应该是用户账号的意思吧？如果是，应该改成user_id，并且可以直接用它做主键。当一个字段唯一时，就可以做主键了，不需要第一个id字段，或者直接把acccount删了，把id看作用户账号。另外用户id最好是int，string比较难操作。

2021-01-19 10:02 UTC, JacksieCheung commented on db.sql
> +    publisherID int ,
user_id就行了，注意命名规范，后面不再提了

2021-01-19 10:02 UTC, JacksieCheung commented on db.sql
> +    releaseDate date default sysdate,
命名规范

2021-01-19 10:02 UTC, JacksieCheung commented on db.sql
> +    heat int ,
这直译热度有点奇怪。产品的意思是热度只按照帖子点赞数来，那就直接写成like_sum，点赞总数。更好理解

2021-01-19 10:02 UTC, JacksieCheung commented on db.sql
> +    commentatorID int ,
应该改成user_id，方便理解

2021-01-19 10:02 UTC, JacksieCheung commented on db.sql
> +    commentOnID int ,
评论的对象是想法，所以直接idea_id就可以了

2021-01-19 10:02 UTC, JacksieCheung commented on db.sql
> +    beLikedPersonID int ,
likesId是啥？没看懂，建议改得通俗易懂一点

2021-01-19 10:57 UTC, gongna-au commented on db.sql
> +    accountPassword varchar2(255) not null,
收到

2021-01-19 11:02 UTC, gongna-au commented on db.sql
> +    account varchar2(255) not null,
我在想把ID作为标识符，从1，2，3，开始......而把Account单独用来储存QQ账号，例如：2036478155@qq.com这样是不是太冗杂了？

2021-01-19 11:02 UTC, gongna-au commented on db.sql
> +    heat int ,
好哒，已采纳

2021-01-19 11:03 UTC, gongna-au commented on db.sql
> +    commentOnID int ,
好哒，已采纳

2021-01-19 11:06 UTC, gongna-au commented on db.sql
> +    commentatorID int ,
好哒

2021-01-19 11:08 UTC, gongna-au commented on db.sql
> +    beLikedPersonID int ,
likesID 指的是点赞者，belikedPersonID指的是被点赞者，确实读起来太难懂了，我再改改。

2021-01-19 11:46 UTC, JacksieCheung commented on db.sql
> +    account varchar2(255) not null,
那这个id字段就是user_id，那一串东西不叫qq号吧？叫邮箱。如果有存储邮箱的需求，是可以存储的。如果没有这个需求就没必要了。

2021-01-23 04:08 UTC, JacksieCheung commented on docs/swagger/swagger.yaml
> +
对比一下示例就可以很容易发现这里少了一行 path:

2021-01-23 04:08 UTC, JacksieCheung commented on docs/swagger/swagger.yaml
> +           schema:
这里`schema:`应该和上面的`in: body`对齐，下面也是，不然会报错

2021-01-23 04:08 UTC, JacksieCheung commented on docs/swagger/swagger.yaml
> +    post:
同一个路径下面不能出现相同的方法。后面很多地方都有这个问题

2021-01-23 09:42 UTC, gongna-au commented on docs/swagger/swagger.yaml
> +           schema:
已改

2021-01-23 09:43 UTC, gongna-au commented on docs/swagger/swagger.yaml
> +    post:
这么说，我需要多写几个路径？

2021-01-24 01:43 UTC, JacksieCheung requested changes

2021-01-24 01:43 UTC, JacksieCheung commented on router/router.go
> +  engine.POST("/register",func (context *gin.Context) {
缩进？

2021-01-24 01:43 UTC, JacksieCheung commented on router/router.go
> +	password,exist := context.GetPostForm("password")
我们规定前后端传输要用json，不用postform。所以因该改成json格式接收

2021-01-24 01:43 UTC, JacksieCheung commented on router/router2.go
> +}
你这程序100%不能跑，这段为啥写在函数体外面？

2021-01-24 01:43 UTC, JacksieCheung commented on router/router2.go
> +	"github.com/gin"
gin的包不叫这个吧？

2021-01-24 01:43 UTC, JacksieCheung commented on router/router2.go
> +	engine := gin.Default()
main函数不应该在这个文件夹，应该在项目根目录

2021-01-24 02:33 UTC, gongna-au commented on router/router.go
> +	password,exist := context.GetPostForm("password")
好哒

2021-01-24 02:34 UTC, gongna-au commented on router/router2.go
> +	"github.com/gin"
好像是VScode自动拉取的

2021-01-24 09:44 UTC, merged